# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API endpoint to get an id from a BGS simulation sample

Resources:
    GetIdFromBgsSimulationSampleFunction2:
        Type: AWS::Serverless::Function
        Properties:
            Handler: bgs-get-id-from-sample.default
            Runtime: nodejs16.x
            CodeUri: ./dist/bgs-get-id-from-sample
            Timeout: 2
            Layers:
                - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - SecretsManagerReadWrite
                - AmazonSESFullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-bgs-get-id-from-sample-2
            AutoPublishAlias: live
            FunctionUrlConfig:
                AuthType: NONE
