# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API endpoint to get an id from a BGS simulation sample

Globals:
    Api:
        # API Gateway regional endpoints
        EndpointConfiguration: EDGE

Resources:
    GetIdFromBgsSimulationSampleFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: bgs-get-id-from-sample.default
            Runtime: nodejs10.x
            Timeout: 20
            MemorySize: 128
            CodeUri: ./dist/bgs-get-id-from-sample
            # https://stackoverflow.com/questions/39144688/aws-lambda-invoke-not-calling-another-lambda-function-node-js
            # VpcConfig:
            #     SecurityGroupIds:
            #         - sg-0ed63616362bf1a30
            #     SubnetIds:
            #         - subnet-0b36da5c19637a351
            #         - subnet-0b730ca9af74a95dd
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-save-bgs-simulation-sample
            Events:
                GetMatchStatsResource:
                    Type: Api
                    Properties:
                        Path: /{proxy+}
                        Method: any

Outputs:
    GetIdFromBgsSimulationSampleApi:
        Description: URL to get an id from a BGS simulation sample
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
        Export:
            Name: GetIdFromBgsSimulationSampleApi
